module.exports = {
  imageURL: String,
  videoURL: String,
  productId: { type: String, index: true, unique: true },
  productCategories: [],
  productType: String,
  productAmazonLink: String,
  productAliexpressLink: String,
  productLink: String,
  productName: String,
  productRating: String,
  productPrice: String,
  productSales: String,
  productOrdersPrice: String,
  productOrdersRanking: String,
  productDaily: String,
  productDailyRank: String,
  productOverall: String,
  productOverallRank: String,
  // _productRating: Number,
  _productPrice: Number,
  _productSales: Number,
  _productOrdersPrice: Number,
  _productOrdersRanking: Number,
  _productDaily: Number,
  _productDailyRank: Number,
  _productOverall: Number,
  _productOverallRank: Number,
};
