module.exports = {
  hot: { type: Boolean, default: false },
  new: { type: Boolean, default: false },
  trend: { type: Boolean, default: false },
  rise: { type: Boolean, default: false },
  imageURL: String,
  videoURL: String,
  productId: { type: String, index: true, unique: true },
  productType: String,
  productLink: String,
  productName: String,
  productRating: String,
  productPrice: String,
  productCategories: [],
  productFlags: [],
  productShips: [],
  productSite: String,
  productSales: String,
  productOrdersPrice: String,
  productOrdersRanking: String,
  productDaily: String,
  productDailyRank: String,
  productOverall: String,
  productOverallRank: String,
  videoPosterURL: String,
  addedLabel: String,
  foundLabel: String,
  productOrders: Number,
  productSellingPrice: Number,
  productProfitMargin: Number,
  productTotalSalesCount: Number,
  productSupplieCount: Number,
  productStoreSellingCount: Number,
  productInsightRating: String,
  productFaceBookAds: String,
  productAmazonAds: String,
  productYoutubeAds: String,
  productOrdersStatistics: {},
  productInsights: [],
  productCompetition: {},
  productTopCustomerCountry: {},
  productStoresCountryBreakdown: {},
  productSellingStores: [],
  productSupplies: [],
  // _productRating: Number,
  _productPrice: Number,
  _productSales: Number,
  _productOrdersPrice: Number,
  _productOrdersRanking: Number,
  _productDaily: Number,
  _productDailyRank: Number,
  _productOverall: Number,
  _productOverallRank: Number,
};
